<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\Images\cat.jpg" />
    <None Remove="Views\Images\TheMoviesStart.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoviesG5.Core\MoviesG5.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Views\Images\cat.jpg" />
    <Resource Include="Views\Images\TheMoviesStart.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
